version: "3" 
services: 
  node:
    build: .
    image: docker-wallarm-node
    environment:
      - WALLARM_API_CA_VERIFY=${WALLARM_API_CA_VERIFY}
      - WALLARM_API_HOST=${WALLARM_API_HOST}
      - WALLARM_API_TOKEN=${WALLARM_API_TOKEN}
      - NGINX_PORT=80
      - NGINX_BACKEND=${NGINX_BACKEND}
      - POSTANALYTIC_ADDRESS="postanalytics:3313"
      - WALLARM_MODE=block
  
  postanalytics:
    build: .
    image: docker-wallarm-node
    environment:
      - WALLARM_API_CA_VERIFY=${WALLARM_API_CA_VERIFY}
      - WALLARM_API_HOST=${WALLARM_API_HOST}
      - WALLARM_API_TOKEN=${WALLARM_API_TOKEN}
      - POSTANALYTIC_ONLY=true
      - HOST=0.0.0.0
